import pygame
import Interactions
from Inventory import Item

class Overlay:
    def __init__(self, x, y, image, enabled=True): # no scale needed; size is pre-determined for the sake of the game
        width = image.get_width()
        height = image.get_height()
        self.image = pygame.transform.scale(image, (int(width), int(height)))
        self.rect = self.image.get_rect(topleft=(x, y))
        self.enabled = enabled
        self.removed = False # just a super version (for locks)

    def draw(self, screen):
        if self.enabled and not self.removed:
            screen.blit(self.image, (self.rect.x, self.rect.y))

    def enable(self, boolean : bool):
        self.enabled = boolean

class Scene:
    def __init__(self, /,*, background, interactions=[], overlays=dict(), name=""):
        self.background = background
        self.interactions = interactions
        self.overlays = overlays
        self.name = name # only reserved for main 1 to 4

    def change_bg(self, background):
        self.background = background

Items = {
    "Flathead Screwdriver" : Item(618,362, pygame.image.load("Images/Items/flatheadScrewdriver.png").convert_alpha(), 1,
        name = "Flathead Screwdriver",
        bg_image = pygame.image.load("Images/Scenes/Cabinet/Screwdriver.png").convert_alpha(),
    ),
    "Phillips Screwdriver" : Item(0,0, pygame.image.load("Images/Items/phillipsScrewdriver.png").convert_alpha(), 1,
        name = "Phillips Screwdriver",
    ),
    "Hammer" : Item(578,421, pygame.image.load("Images/Items/hammer.png").convert_alpha(), 1,
        name = "Hammer",
        bg_image = pygame.image.load("Images/Scenes/Desk/Hammer.png").convert_alpha(),
    ),
    "Electric Tape" : Item(610,578, pygame.image.load("Images/Items/tape.png").convert_alpha(), 1,
        name = "Electric Tape",
        bg_image = pygame.image.load("Images/Scenes/Desk/Tape.png").convert_alpha(),
    ),
    "Laptop Charger" : Item(626,488, pygame.image.load("Images/Items/wire.png").convert_alpha(), 1,
        name = "Laptop Charger",
        bg_image = pygame.image.load("Images/Scenes/Cabinet/Wires.png").convert_alpha(),
    ),
    "Silver Key" : Item(0,0, pygame.image.load("Images/Items/silverkey.png").convert_alpha(), 1,
        name = "Silver Key",
    ),
    "Gold Key" : Item(712,494, pygame.image.load("Images/Items/goldkey.png").convert_alpha(), 1,
        name = "Gold Key",
        bg_image = pygame.image.load("Images/Scenes/Vent/GoldKey.png").convert_alpha(),
    ),
    "Chair" : Item(0,0, pygame.image.load("Images/Items/chair.png").convert_alpha(), 1,
        name = "Chair",
    ),
    "Broom" : Item(0,0, pygame.image.load("Images/Items/broom.png").convert_alpha(), 1,
        name = "Broom",
    ),
    "Notes" : Item(0,0, pygame.image.load("Images/Items/paper.png").convert_alpha(), 1,
        name = "Notes",
    ),
}

Scenes = {
    # PRIMARY
    "Front_Room" : Scene(
        background = pygame.image.load('Images/Scenes/Main1/Scene.png'),
        name = "Front_Room",
        interactions = [
            Interactions.Transition(49,618,75,75,
                scene = "Behind_Cabinet",
                cursor = "Back",
                text = "Cabinet?",
            ),
            Interactions.Transition(0,0,100,825, # LEFT
                scene = "Left_Room",
                cursor = "Left",
            ),
            Interactions.Transition(1466-100,0,100,825, # RIGHT
                scene = "Right_Room",
                cursor = "Right",
            ),
            
            Interactions.Transition(43,404,334,262,
                scene = "Front_Cabinet",
                text = "Cabinet",
            ),
            Interactions.Transition(831,378,237,148,
                scene = "Desk",
                text = "Desk",
            ),
            Interactions.Transition(668,358,80,56,
                scene = "Power",
                text = "Powerbox",
            ),
            Interactions.Transition(877,295,57,57,
                scene = "Clock",
                text = "Clock",
            ),
            Interactions.Transition(791,445,39,64,
                scene = "TrashBin",
                text = "Trash Bin",
            ),
            Interactions.Vent_Transition(321,219,70,72,
                scene = "Vent",
                text = "Vent",
            ),
        ],
        overlays = {
            "SilverKey" : Overlay(72, 663, pygame.image.load('Images/Scenes/Main1/SilverKey.png'), True),
            "SilverLock" : Overlay(364, 491, pygame.image.load('Images/Scenes/Main1/SilverLock.png'), True),
            "GoldLock" : Overlay(919, 467, pygame.image.load('Images/Scenes/Main1/GoldLock.png'), True),
            "Wire" : Overlay(0, 0, pygame.image.load('Images/Scenes/Main1/Wire.png'), False),
        },
    ),
    "Right_Room" : Scene(
        background = pygame.image.load('Images/Scenes/Main2/Scene.png'),
        name = "Right_Room",
        interactions = [
            Interactions.Transition(167,517,128,129,
                scene = "TrashBin",
                cursor = "Back",
                text = "Trash Bin",
            ),
            Interactions.Transition(221,387,297,225,
                scene = "Desk",
                text = "Desk",
            ),
            Interactions.Transition(246,259,70,86,
                scene = "Clock",
                text = "Clock",
            ),
            Interactions.Transition(827,256,158,203,
                scene = "Poster",
                text = "Poster",
            ),
            Interactions.Transition(727,307,82,50,
                scene = "Calendar",
                text = "Calendar",
            ),
            Interactions.Broom_Interaction(1047,374,67,165,
                cursor = "Hand",
                text = "Broom",
            ),

            Interactions.Transition(0,0,100,825, # LEFT
                scene = "Front_Room",
                cursor = "Left",
            ),
            Interactions.Transition(1466-100,0,100,825, # RIGHT
                scene = "Back_Room",
                cursor = "Right",
            ),
        ],
        overlays = {
            "GoldLock" : Overlay(0, 0, pygame.image.load('Images/Scenes/Main2/GoldLock.png'), True),
            "Wire" : Overlay(0, 0, pygame.image.load('Images/Scenes/Main2/Wire.png'), False),
        },
    ),
    "Back_Room" : Scene(
        background = pygame.image.load('Images/Scenes/Main3/Scene.png'),
        name = "Back_Room",
        interactions = [
            Interactions.Transition(244,213,214,362,
                scene = "Poster",
                text = "Poster",
            ),
            Interactions.Transition(100,264,130,90,
                scene = "Calendar",
                text = "Calendar",
            ),
            Interactions.Transition(799,441,82,77,
                scene = "Safe",
                text = "Safe",
            ),
            Interactions.Transition(1085,382,318,279,
                scene = "Front_Cabinet",
                text = "Cabinet",
            ),
            Interactions.Broom_Interaction(438,373,57,133,
                cursor = "Hand",
                text = "Broom",
            ),

            Interactions.Transition(0,0,100,825, # LEFT
                scene = "Right_Room",
                cursor = "Left",
            ),
            Interactions.Transition(1466-100,0,100,825, # RIGHT
                scene = "Left_Room",
                cursor = "Right",
            ),
            Interactions.Text(550,291,338,109,
                text = '"NO ESCAPE"'
            ),
        ],
        overlays = {
            "SilverLock" : Overlay(1165, 519, pygame.image.load('Images/Scenes/Main3/SilverLock.png'), True),
        },
    ),
    "Left_Room" : Scene(
        background = pygame.image.load('Images/Scenes/Main4/Scene.png'),
        name = "Left_Room",
        interactions = [
            Interactions.Transition(667,377,101,144,
                scene = "Front_Cabinet",
                text = "Cabinet",
            ),
            Interactions.Transition(273,468,139,103,
                scene = "Safe",
                text = "Safe",
            ),
            Interactions.Transition(1188,355,153,109,
                scene = "Power",
                text = "Powerbox",
            ),
            Interactions.Vent_Transition(863,254,85,52,
                scene = "Vent",
                text = "Vent",
            ),
            Interactions.Chair_Interaction(541,384,74,128,
                cursor = "Hand",
                text = "Chair",
            ),
            Interactions.Chair_Place_Interaction(853,362,127,159, # [INDEX 5; DO NOT MOVE]
            ),

            Interactions.Transition(0,0,100,825, # LEFT
                scene = "Back_Room",
                cursor = "Left",
            ),
            Interactions.Transition(1466-100,0,100,825, # RIGHT
                scene = "Front_Room",
                cursor = "Right",
            ),
        ],
        overlays = {
            "SilverLock" : Overlay(750, 444, pygame.image.load('Images/Scenes/Main4/SilverLock.png'), True),
            "GoldLock" : Overlay(1431, 712, pygame.image.load('Images/Scenes/Main4/GoldLock.png'), True),
        },
    ),
    # SECONDARY
    "Front_Cabinet" : Scene(
        background = pygame.image.load('Images/Scenes/Cabinet/Scene.png'),
        interactions = [
            Interactions.Chair_Interaction(95,91,341,424,
                cursor = "Hand",
                text = "Chair",
            ),
            Interactions.Cabinet(509,163,437,115,
                [35,501, 1352,274],
                overlay = {"Cabinet1_Open"},
                priority = 1,
            ),
            Interactions.Item_Cabinet(539,297,379,87,
                [352,587, 743,140],
                overlay = {"Cabinet1", "Cabinet2_Open"},
                priority = 2,
                item = "Flathead Screwdriver",
            ),
            Interactions.Silver_Locked_Cabinet(563,396,341,167,
                [470,632, 520,163],
                overlay = {"Cabinet1", "Cabinet2", "Cabinet3_Open"},
                priority = 3,
                item = "Laptop Charger",
            ),
            Interactions.Transition(0,625,1466,200,
                scene = "Previous",
                cursor = "Back",
            ),
        ],
        overlays = {
            "Cabinet1" : Overlay(0, 0, pygame.image.load('Images/Scenes/Cabinet/Cabinet1.png'), True),
            "Cabinet1_Open" : Overlay(0, 0, pygame.image.load('Images/Scenes/Cabinet/Cabinet1Open.png'), False),
            "Cabinet2" : Overlay(0, 0, pygame.image.load('Images/Scenes/Cabinet/Cabinet2.png'), True),
            "Cabinet2_Open" : Overlay(0, 0, pygame.image.load('Images/Scenes/Cabinet/Cabinet2Open.png'), False),
            "Cabinet3" : Overlay(0, 0, pygame.image.load('Images/Scenes/Cabinet/Cabinet3.png'), True),
            "Cabinet3_Open" : Overlay(0, 0, pygame.image.load('Images/Scenes/Cabinet/Cabinet3Open.png'), False),
            "SilverLock" : Overlay(875, 410, pygame.image.load('Images/Scenes/Cabinet/SilverLock.png'), True),
        },
    ),
    "Behind_Cabinet" : Scene(
        background = pygame.image.load('Images/Scenes/Cabinet/BehindCabinet.png'),
        interactions = [
            Interactions.SilverKey_Interaction(837,364,100,100,
                cursor = "Hand",
                text = "Silver Key",
            ),
            Interactions.Transition(0,575,1466,250,
                scene = "Previous",
                cursor = "Back",
            ),
        ],
    ),
    "Desk" : Scene(
        background = pygame.image.load('Images/Scenes/Desk/Scene.png'),
        interactions = [
            Interactions.Transition(220,382,213,262,
                scene = "TrashBin",
                text = "Trash Bin",
            ),
            Interactions.Laptop_Transition(677,108,226,173,
                scene = "Laptop",
                text = "Laptop",
            ),
            Interactions.Item_Cabinet(576,376,91,91,
                [783,562, 120,120],
                overlay = {"Cabinet1_Open"},
                priority = 1,
                item = "Hammer",
            ),
            Interactions.Gold_Locked_Cabinet(690,443,55,119,
                [839,563, 52,127],
                overlay = {"Cabinet1", "Cabinet2_Open"},
                priority = 2,
                item = "Electric Tape",
            ),
            Interactions.Transition(0,725,1466,100,
                scene = "Previous",
                cursor = "Back",
            ),
        ],
        overlays = {
            "Cabinet1" : Overlay(0, 0, pygame.image.load('Images/Scenes/Desk/Cabinet1.png'), True),
            "Cabinet1_Open" : Overlay(0, 0, pygame.image.load('Images/Scenes/Desk/Cabinet1Open.png'), False),
            "Cabinet2" : Overlay(0, 0, pygame.image.load('Images/Scenes/Desk/Cabinet2.png'), True),
            "Cabinet2_Open" : Overlay(0, 0, pygame.image.load('Images/Scenes/Desk/Cabinet2Open.png'), False),
            "GoldLock" : Overlay(731, 449, pygame.image.load('Images/Scenes/Desk/GoldLock.png'), True),
            "Wire" : Overlay(0, 0, pygame.image.load('Images/Scenes/Desk/Wire.png'), False),
        },
    ),
    "Safe" : Scene(
        background = pygame.image.load('Images/Scenes/Safe/Scene.png'),
        interactions = [
            Interactions.Safe_Code(737,330,123,35), # INDEX 0 (DO NOT MOVE)
            Interactions.Safe_Button(734, 377, pygame.image.load('Images/Scenes/Safe/Button1.png'), 1,
                input = 1,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button1Clicked.png'),
            ),
            Interactions.Safe_Button(778, 377, pygame.image.load('Images/Scenes/Safe/Button2.png'), 1,
                input = 2,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button2Clicked.png'),
            ),
            Interactions.Safe_Button(822, 377, pygame.image.load('Images/Scenes/Safe/Button3.png'), 1,
                input = 3,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button3Clicked.png'),
            ),
            Interactions.Safe_Button(734, 421, pygame.image.load('Images/Scenes/Safe/Button4.png'), 1,
                input = 4,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button4Clicked.png'),
            ),
            Interactions.Safe_Button(778, 421, pygame.image.load('Images/Scenes/Safe/Button5.png'), 1,
                input = 5,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button5Clicked.png'),
            ),
            Interactions.Safe_Button(822, 421, pygame.image.load('Images/Scenes/Safe/Button6.png'), 1,
                input = 6,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button6Clicked.png'),
            ),
            Interactions.Safe_Button(734, 465, pygame.image.load('Images/Scenes/Safe/Button7.png'), 1,
                input = 7,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button7Clicked.png'),
            ),
            Interactions.Safe_Button(778, 465, pygame.image.load('Images/Scenes/Safe/Button8.png'), 1,
                input = 8,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button8Clicked.png'),
            ),
            Interactions.Safe_Button(822, 465, pygame.image.load('Images/Scenes/Safe/Button9.png'), 1,
                input = 9,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button9Clicked.png'),
            ),
            Interactions.Safe_Button(734, 509, pygame.image.load('Images/Scenes/Safe/ButtonC.png'), 1,
                input = "C",
                clicked_image = pygame.image.load('Images/Scenes/Safe/ButtonCClicked.png'),
            ),
            Interactions.Safe_Button(778, 509, pygame.image.load('Images/Scenes/Safe/Button0.png'), 1,
                input = 0,
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button0Clicked.png'),
            ),
            Interactions.Safe_Button(822, 509, pygame.image.load('Images/Scenes/Safe/Button#.png'), 1,
                input = "#",
                clicked_image = pygame.image.load('Images/Scenes/Safe/Button#Clicked.png'),
            ),
            Interactions.Safe_Transition(496,336,49,186,
                scene = "Safe_Opened",
            ),
            
            Interactions.Transition(0,725,1466,100,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,1466,100,
                scene = "Previous",
            ),
            Interactions.Transition(0,0,200,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1266,0,200,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
    ),
    "Safe_Opened" : Scene(
        background = pygame.image.load('Images/Scenes/Safe/Open.png'),
        interactions = [       
            Interactions.Paper_Interaction(660,519,129,56,
                cursor = "Hand",
                text = "Notes",
            ),

            Interactions.Transition(0,725,1466,100,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,1466,100,
                scene = "Previous",
            ),
            Interactions.Transition(0,0,200,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1266,0,200,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
        overlays = {
            "Paper" : Overlay(0, 0, pygame.image.load('Images/Scenes/Safe/Paper.png'), True),
        },
    ),
    "Power" : Scene(
        background = pygame.image.load('Images/Scenes/Power/Scene.png'),
        interactions = [
            Interactions.Screw(462,242,
                type = "Phillips"
            ),
            Interactions.Screw(989,242,
                type = "Phillips"
            ),
            Interactions.Screw(462,568,
                type = "Phillips"
            ),
            Interactions.Screw(989,568,
                type = "Phillips"
            ),

            Interactions.Transition(0,625,1466,200,
                scene = "Previous",
                cursor = "Back",
            ),
        ],
    ),
    "Poster" : Scene(
        background = pygame.image.load('Images/Scenes/Poster/Scene.png'),
        interactions = [
            Interactions.Transition(210,285,246,159,
                scene = "Calendar",
                text = "Calendar",
            ),
            Interactions.Transition(882,653,50,50,
                scene = "Poster_Removed",
                cursor = "Hand",
            ),
            Interactions.Transition(0,725,1466,100,
                scene = "Previous",
                cursor = "Back",
            ),
        ],
        overlays = {
            "Broom" : Overlay(0, 0, pygame.image.load('Images/Scenes/Poster/Broom.png'), True),
        },
    ),
    "Poster_Removed" : Scene(
        background = pygame.image.load('Images/Scenes/Poster/NoPoster.png'),
        interactions = [
            Interactions.Wall_Interaction(583,220,297,384,
                cursor = "Hand",
            ),

            Interactions.Transition(210,285,246,159,
                scene = "Calendar",
                text = "Calendar",
            ),
            Interactions.Transition(0,725,1466,100,
                scene = "Previous",
                cursor = "Back",
            ),
        ],
        overlays = {
            "Broom" : Overlay(0, 0, pygame.image.load('Images/Scenes/Poster/Broom.png'), True),
        },
    ),
    "Vent" : Scene(
        background = pygame.image.load('Images/Scenes/Vent/Scene.png'),
        interactions = [
            Interactions.Screw(384,240,
                type = "Flathead"
            ),
            Interactions.Screw(1068,240,
                type = "Flathead"
            ),
            Interactions.Screw(384,570,
                type = "Flathead"
            ),
            Interactions.Screw(1068,570,
                type = "Flathead"
            ),
            Interactions.Vent_Interaction(417,255,633,316,
                scene = "Vent_Removed",
                cursor = "Hand",
            ),

            Interactions.Transition(0,650,1466,175,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,200,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1266,0,200,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
    ),
    "Vent_Removed" : Scene(
        background = pygame.image.load('Images/Scenes/Vent/Open.png'),
        interactions = [
            Interactions.GoldKey_Interaction(699,472,50,50,
                cursor = "Hand",
                text = "Gold Key",
            ),

            Interactions.Transition(0,650,1466,175,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,200,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1266,0,200,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
        overlays = {
            "GoldKey" : Overlay(712, 494, pygame.image.load('Images/Scenes/Vent/GoldKey.png'), True),
        },
    ),
    # ---
    "Calendar" : Scene(
        background = pygame.image.load('Images/Scenes/CalendarScene.png'),
        interactions = [
            Interactions.Transition(0,700,1466,125,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,200,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1266,0,200,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
    ),
    "Clock" : Scene(
        background = pygame.image.load('Images/Scenes/ClockScene.png'),
        interactions = [
            Interactions.Transition(0,700,1466,125,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,400,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1066,0,400,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
    ),
    "Laptop" : Scene(
        background = pygame.image.load('Images/Scenes/Laptop/Scene.png'),
        interactions = [
            Interactions.Laptop_Textbox(614,405,238,26), # INDEX 0 (do not move)
            Interactions.Laptop_Switch(330,231,62,27), # INDEX 1 (do not move)

            Interactions.Transition(0,750,1466,75,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,200,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1266,0,200,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
        overlays = {
            "Incorrect" : Overlay(0, 0, pygame.image.load('Images/Scenes/Laptop/IncorrectPrompt.png'), False),
            "OffSwitch" : Overlay(331, 232, pygame.image.load('Images/Scenes/Laptop/OffSwitch.png'), False),
            "OnSwitch" : Overlay(331, 232, pygame.image.load('Images/Scenes/Laptop/OnSwitch.png'), False),
        },
    ),
    "TrashBin" : Scene(
        background = pygame.image.load('Images/Scenes/TrashBinScene.png'),
        interactions = [
            Interactions.Transition(0,0,1466,100,
                scene = "Previous",
            ),
            Interactions.Transition(0,750,1466,75,
                scene = "Previous",
                cursor = "Back",
            ),
            Interactions.Transition(0,0,400,825,
                scene = "Previous",
                cursor = "Left",
            ),
            Interactions.Transition(1066,0,400,825,
                scene = "Previous",
                cursor = "Right",
            ),
        ],
    ),
}